This project was done by: 1633-Ameko Mawulolo Koku, 
    1619-Akinlabi Emmanuel Olutayo and 
    1601 - Haward Ketoyo Msatsi


In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
test =  pd.read_csv("bike_test.csv")
train =  pd.read_csv("bike_train.csv")

In [5]:
#test.info()
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10886 entries, 0 to 10885
Data columns (total 17 columns):
year          10886 non-null int64
month         10886 non-null int64
day           10886 non-null int64
hour          10886 non-null int64
minute        10886 non-null int64
second        10886 non-null int64
season        10886 non-null int64
holiday       10886 non-null int64
workingday    10886 non-null int64
weather       10886 non-null int64
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
registered    10886 non-null int64
count         10886 non-null int64
dtypes: float64(3), int64(14)

In [6]:
features = list(train.columns.values)
print features


['year', 'month', 'day', 'hour', 'minute', 'second', 'season', 'holiday', 'workingday', 'weather', 'temp', 'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count']


In [7]:
train['season'].unique()

array([1, 2, 3, 4])

In [8]:
train.describe()

year         month           day          hour  minute  second  \
count  10886.000000  10886.000000  10886.000000  10886.000000   10886   10886   
mean    2011.501929      6.521495      9.992559     11.541613       0       0   
std        0.500019      3.444373      5.476608      6.915838       0       0   
min     2011.000000      1.000000      1.000000      0.000000       0       0   
25%     2011.000000      4.000000      5.000000      6.000000       0       0   
50%     2012.000000      7.000000     10.000000     12.000000       0       0   
75%     2012.000000     10.000000     15.000000     18.000000       0       0   
max     2012.000000     12.000000     19.000000     23.000000       0       0   

             season       holiday    workingday       weather         temp  \
count  10886.000000  10886.000000  10886.000000  10886.000000  10886.00000   
mean       2.506614      0.028569      0.680875      1.418427     20.23086   
std        1.116174      0.166599      0.466159      0.633839      7.79159   
min        1.000000      0.000000      0.000000      1.000000      0.82000   
25%        2.000000      0.000000      0.000000      1.000000     13.94000   
50%        3.000000      0.000000      1.000000      1.000000     20.50000   
75%        4.000000      0.000000      1.000000      2.000000     26.24000   
max        4.000000      1.000000      1.000000      4.000000     41.00000   

              atemp      humidity     windspeed        casual    registered  \
count  10886.000000  10886.000000  10886.000000  10886.000000  10886.000000   
mean      23.655084     61.886460     12.799395     36.021955    155.552177   
std        8.474601     19.245033      8.164537     49.960477    151.039033   
min        0.760000      0.000000      0.000000      0.000000      0.000000   
25%       16.665000     47.000000      7.001500      4.000000     36.000000   
50%       24.240000     62.000000     12.998000     17.000000    118.000000   
75%       31.060000     77.000000     16.997900     49.000000    222.000000   
max       45.455000    100.000000     56.996900    367.000000    886.000000   

              count  
count  10886.000000  
mean     191.574132  
std      181.144454  
min        1.000000  
25%       42.000000  
50%      145.000000  
75%      284.000000  
max      977.000000  

[8 rows x 17 columns]

In [9]:
from pandas.tools.plotting import scatter_matrix
import numpy as np
%matplotlib inline
#matplotlib.style.use('ggplot')
#scatter_matrix(train.iloc[:, 0:17], alpha=0.2,figsize=(15, 15), diagonal='kde')

#import seaborn as sns; sns.set(style="ticks", color_codes=True)
#iris = sns.load_dataset("iris")
#g = sns.pairplot(train.iloc[:, 0:16])


From the above plot, we observe that there's a high correlation between temp and atemp. Co-linearity between two predictor variables leads to redundancy and hence bad performance so we must discard one. 
We also judge that other variables such as year, month, day, minutes, seconds, casual and registered are intuitively not valid predictors of the number of hiring on bikes in a day.

In [10]:
# = train['hour', 'season', 'holiday', 'workingday', 'weather', 'temp', 'humidity', 'windspeed']
feature_select  = ['hour', 'season', 'holiday', 'workingday', 'weather', 'temp', 'humidity', 'windspeed']
new_train = train[feature_select] #selecting important features
target  = train['count'] #defining target

Training a decision regressor

In [11]:
from sklearn.tree import DecisionTreeRegressor
#from sklearn.preprocessing import scale
#new_train = scale(new_train)
dtr = DecisionTreeRegressor()
dtr.fit(new_train, target)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

It turns out that our test data does not have actual target provided in the dataset hence we resort to subdividing our training data into train, cross validation and test to evaluate the performance of our machine

In [12]:
from sklearn.cross_validation import cross_val_score

###use the cross_val_score function on the whole dataset
cv_scores_1 = cross_val_score(dtr, new_train , target, cv=3)
print cv_scores_1
#When calling the cross_val_score it returns one score per fold
#As by default the function uses a three-fold separation you have three value
###Compute and print the mean and the standard deviation of the cross_val_score function
#print 'Mean scores is: ', np.mean(cv_scores_1)
#print 'Standard Deviation of scores is: ', np.std(cv_scores_1)
print "Accuracy: %0.2f (+/- %0.2f)" % (cv_scores_1.mean(), cv_scores_1.std() * 2)


[ 0.08936965  0.34919922  0.62465898]
Accuracy: 0.35 (+/- 0.44)


Obviously this was not a good performance, so we judge that it was because the dataset contained some irrelevant features and hence we resort to automatic feature selection using RFE.

"Given an external estimator that assigns weights to features (e.g., the coefficients of a linear model), the goal of recursive feature elimination (RFE) is to select features by recursively considering smaller and smaller sets of features. First, the estimator is trained on the initial set of features and weights are assigned to each one of them. Then, features whose absolute weights are the smallest are pruned from the current set features. That procedure is recursively repeated on the pruned set until the desired number of features to select is eventually reached."

In [13]:
#from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeRegressor
# load the iris datasets
#dataset = datasets.load_iris()
# create a base classifier used to evaluate a subset of attributes
model = DecisionTreeRegressor()
# create the RFE model and select 3 attributes
rfe = RFE(model, 3)
rfe = rfe.fit(train.iloc[:,0:16], train['count'])
# summarize the selection of the attributes
print(rfe.support_)
print(rfe.ranking_)

[False False  True False False False False False False False False False
 False False  True  True]
[10  2  1  6 14 13  8 12 11  9  5  7  3  4  1  1]


As observed above, only features 'day','registered', 'casual', 'humidity' are relevant for the prediction task though humidity ranked 2, we would use it as it intuitively has effect on people's decision to ride a bike especially among asthmatics

In [14]:
print train.iloc[:,0:16].columns
features = ['month', 'day', 'humidity']
newest_train = train[features]
#newest_train

Index([u'year', u'month', u'day', u'hour', u'minute', u'second', u'season', u'holiday', u'workingday', u'weather', u'temp', u'atemp', u'humidity', u'windspeed', u'casual', u'registered'], dtype='object')


In [15]:
from sklearn.cross_validation import cross_val_score

###use the cross_val_score function on the whole dataset
cv_scores_1 = cross_val_score(dtr, newest_train , target, cv=3)
print cv_scores_1
#When calling the cross_val_score it returns one score per fold
#As by default the function uses a three-fold separation you have three value
###Compute and print the mean and the standard deviation of the cross_val_score function
#print 'Mean scores is: ', np.mean(cv_scores_1)
#print 'Standard Deviation of scores is: ', np.std(cv_scores_1)
print "Accuracy: %0.2f (+/- %0.2f)" % (cv_scores_1.mean(), cv_scores_1.std() * 2)

[-1.89476239 -0.82080543 -0.21528335]
Accuracy: -0.98 (+/- 1.39)


Could ensemble methods give us a better performance as always? 
Now using emsemble methods

In [16]:
###Import the "RandomForestClassifier" classifier
from sklearn.ensemble import RandomForestClassifier
###Train it on the training set
rfc = RandomForestClassifier()
rfc.fit(newest_train,target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [17]:
from sklearn.cross_validation import cross_val_score

###use the cross_val_score function on the whole dataset
cv_scores_1 = cross_val_score(rfc, newest_train , target, cv=3)
print cv_scores_1
#When calling the cross_val_score it returns one score per fold
#As by default the function uses a three-fold separation you have three value
###Compute and print the mean and the standard deviation of the cross_val_score function
print "Accuracy: %0.2f (+/- %0.10f)" % (cv_scores_1.mean(), cv_scores_1.std() * 2)

/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=3.
  % (min_labels, self.n_folds)), Warning)


[ 0.00382068  0.00248963  0.00358744]
Accuracy: 0.00 (+/- 0.0011607112)


This wasn't any better. Could the almighty gradient boosting help us?

In [18]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
bagging = BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5)

In [19]:
bagging.fit(newest_train,target)

BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
         bootstrap=True, bootstrap_features=False, max_features=0.5,
         max_samples=0.5, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [20]:
from sklearn.cross_validation import cross_val_score

###use the cross_val_score function on the whole dataset
cv_scores_1 = cross_val_score(bagging, newest_train , target, cv=3)
print cv_scores_1
#When calling the cross_val_score it returns one score per fold
#As by default the function uses a three-fold separation you have three value
###Compute and print the mean and the standard deviation of the cross_val_score function
#print 'Mean scores is: ', np.mean(cv_scores_1)
#print 'Standard Deviation of scores is: ', np.std(cv_scores_1)
print "Accuracy: %0.2f (+/- %0.2f)" % (cv_scores_1.mean(), cv_scores_1.std() * 2)

[ 0.00993377  0.006639    0.00896861]
Accuracy: 0.01 (+/- 0.00)


This wasn't any better either. Our justification of this phenomenon is that, the data has a time series nature and hence depends on seasonality, with regards to this we cannot achieve a good performance by select sub-samples randomly and hoping to get a well trended results. It does not work!

Obviously the  random forest is doing a much better job, so we optimize it for our prediction



In [21]:
from sklearn.grid_search import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

###Example of a parameter grid dictionary, run it once and then include more parameters in p_grid
p_grid=dict({'criterion':['mse'], 'max_depth': [1, 3, 5, 10, None],
              'random_state': [0,None]})

#grd = GridSearchCV(dtr,cv=3,param_grid= p_grid)
#grd.fit(<training set>,<train set targets>)
rfr=RandomForestRegressor()
grd = GridSearchCV(rfr,cv=3,param_grid=p_grid)
grd.fit(newest_train,target)

GridSearchCV(cv=3, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'random_state': [0, None], 'criterion': ['mse'], 'max_depth': [1, 3, 5, 10, None]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [22]:
print 'Best parameters are: ', grd.best_params_
new_rfr = grd.best_estimator_ #settin the new model

Best parameters are:  {'random_state': None, 'criterion': 'mse', 'max_depth': 3}


In [23]:
new_rfr.fit(newest_train, target)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=3,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [24]:
from sklearn.cross_validation import cross_val_score

###use the cross_val_score function on the whole dataset
cv_scores_1 = cross_val_score(new_dtr, newest_train , target, cv=3)
print cv_scores_1
#When calling the cross_val_score it returns one score per fold
#As by default the function uses a three-fold separation you have three value
###Compute and print the mean and the standard deviation of the cross_val_score function
#print 'Mean scores is: ', np.mean(cv_scores_1)
#print 'Standard Deviation of scores is: ', np.std(cv_scores_1)
print "Accuracy: %0.2f (+/- %0.2f)" % (cv_scores_1.mean(), cv_scores_1.std() * 2)

NameError: name 'new_dtr' is not defined

Now on to our prediction

In [ ]:
new_test = test[features]#ensuring dimensionality fit
prediction_count=new_rfr.predict(new_test)

In [25]:
prediction_count

NameError: name 'prediction_count' is not defined

We think the Random Forest works best and we rather use it for the prediction. Also when prediction turns out to give decimal values, we can justify this as a model bias since it's fundamentally a regression problem. We need to have continuous variables at a target. So in our case we only round it up to the nearest integer value.

In [26]:
prediction_count=np.around(prediction_count.astype(np.int),0)

NameError: name 'prediction_count' is not defined

In [27]:
print prediction_count

NameError: name 'prediction_count' is not defined

In [28]:
with open('prediction.csv', 'w') as csvfile:    
            for count in prediction_count:
                 csvfile.write("{}\n".format(count)) 

NameError: name 'prediction_count' is not defined

Our prediction was saved a file called prediction.csv. Thanks for going through our work!